INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Training and evaluation datasets
BUSI_PATH: "./datasets/BUSI"
BUSI1800_PATH: "./datasets/Breast1800"
LITS_PATH: "./datasets/LITS"
CHAOS_CT_PATH: "./datasets/CHAOS_CT"
MSD_Brain_PATH: "./datasets/MSD_Brain"
BraTS_2018_PATH: "./datasets/BraTS_2018"
LITS_Tumor_PATH: "./datasets/LITS_Tumor"
BTCV_TCIA_SPLEEN: "./datasets/btcv_tcia_spleen"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"